"""project subsystems mode (D-9)

Revision ID: 0a704dda7a76
Revises: 432d6104a9e3
Create Date: 2026-07-14 11:04:17.843859
"""
from alembic import op
import sqlalchemy as sa


revision = '0a704dda7a76'
down_revision = '432d6104a9e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'projects',
        sa.Column('subsystems', sa.String(length=16), nullable=False, server_default=''),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'subsystems')
    # ### end Alembic commands ###
