"""d11 intake sessions + routing events

Revision ID: 0f20cfa5d1ed
Revises: 8fd0034b8653
Create Date: 2026-07-16 10:49:17.889199
"""
from alembic import op
import sqlalchemy as sa


revision = '0f20cfa5d1ed'
down_revision = '8fd0034b8653'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('routing_events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('chosen_sop_id', sa.String(length=32), nullable=True),
    sa.Column('previous_sop_id', sa.String(length=32), nullable=True),
    sa.Column('reason', sa.String(length=300), nullable=False),
    sa.Column('router_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routing_events_created_at'), 'routing_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_routing_events_project_id'), 'routing_events', ['project_id'], unique=False)
    op.create_index(op.f('ix_routing_events_session_id'), 'routing_events', ['session_id'], unique=False)
    op.create_index(op.f('ix_routing_events_tenant_id'), 'routing_events', ['tenant_id'], unique=False)
    op.alter_column('sessions', 'sop_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'sop_id',
               existing_type=sa.VARCHAR(length=32),
               nullable=False)
    op.drop_index(op.f('ix_routing_events_tenant_id'), table_name='routing_events')
    op.drop_index(op.f('ix_routing_events_session_id'), table_name='routing_events')
    op.drop_index(op.f('ix_routing_events_project_id'), table_name='routing_events')
    op.drop_index(op.f('ix_routing_events_created_at'), table_name='routing_events')
    op.drop_table('routing_events')
    # ### end Alembic commands ###
