"""turn instruction_hit flag

Revision ID: 133c2b77914a
Revises: fedba019c93a
Create Date: 2026-07-15 05:46:54.476190
"""
from alembic import op
import sqlalchemy as sa


revision = '133c2b77914a'
down_revision = 'fedba019c93a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('instruction_hit', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'instruction_hit')
    # ### end Alembic commands ###
