"""config_rulesets tables

Revision ID: 21e2e51b824a
Revises: 0f20cfa5d1ed
Create Date: 2026-07-23 04:53:11.298015
"""
from alembic import op
import sqlalchemy as sa


revision = '21e2e51b824a'
down_revision = '0f20cfa5d1ed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_rulesets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'name')
    )
    op.create_index(op.f('ix_config_rulesets_project_id'), 'config_rulesets', ['project_id'], unique=False)
    op.create_index(op.f('ix_config_rulesets_tenant_id'), 'config_rulesets', ['tenant_id'], unique=False)
    op.create_table('config_ruleset_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('ruleset_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ruleset_id'], ['config_rulesets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ruleset_id', 'version')
    )
    op.create_index(op.f('ix_config_ruleset_versions_ruleset_id'), 'config_ruleset_versions', ['ruleset_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_ruleset_versions_ruleset_id'), table_name='config_ruleset_versions')
    op.drop_table('config_ruleset_versions')
    op.drop_index(op.f('ix_config_rulesets_tenant_id'), table_name='config_rulesets')
    op.drop_index(op.f('ix_config_rulesets_project_id'), table_name='config_rulesets')
    op.drop_table('config_rulesets')
    # ### end Alembic commands ###
