"""p0 initial schema

Revision ID: 432d6104a9e3
Revises: 
Create Date: 2026-07-14 07:34:35.142089
"""
from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


revision = '432d6104a9e3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corpora',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('embedding_model', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_corpora_project_id'), 'corpora', ['project_id'], unique=False)
    op.create_index(op.f('ix_corpora_tenant_id'), 'corpora', ['tenant_id'], unique=False)
    op.create_table('data_fetches',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('dependency_name', sa.String(length=200), nullable=False),
    sa.Column('action_name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('speculative', sa.Boolean(), nullable=False),
    sa.Column('predictor_source', sa.String(length=16), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('issued_at_turn', sa.Integer(), nullable=False),
    sa.Column('predicted_turn', sa.Integer(), nullable=False),
    sa.Column('query_text', sa.Text(), nullable=True),
    sa.Column('query_hash', sa.String(length=24), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetch_duration_ms', sa.Integer(), nullable=False),
    sa.Column('payload_summary', sa.String(length=500), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('consumed', sa.Boolean(), nullable=False),
    sa.Column('consumed_at_turn', sa.Integer(), nullable=True),
    sa.Column('wasted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_fetches_project_id'), 'data_fetches', ['project_id'], unique=False)
    op.create_index(op.f('ix_data_fetches_tenant_id'), 'data_fetches', ['tenant_id'], unique=False)
    op.create_index('ix_fetch_session', 'data_fetches', ['session_id', 'created_at'], unique=False)
    op.create_table('pool_picks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('picked_item_ids', sa.JSON(), nullable=False),
    sa.Column('pool_size_at_pick', sa.Integer(), nullable=False),
    sa.Column('rationale', sa.String(length=300), nullable=False),
    sa.Column('pick_duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pool_picks_project_id'), 'pool_picks', ['project_id'], unique=False)
    op.create_index(op.f('ix_pool_picks_session_id'), 'pool_picks', ['session_id'], unique=False)
    op.create_index(op.f('ix_pool_picks_tenant_id'), 'pool_picks', ['tenant_id'], unique=False)
    op.create_table('precedent_traces',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('sop_id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('cohort', sa.String(length=100), nullable=False),
    sa.Column('mood', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('immediate_state', sa.String(length=100), nullable=False),
    sa.Column('immediate_reward', sa.Float(), nullable=False),
    sa.Column('terminal_outcome', sa.String(length=32), nullable=True),
    sa.Column('terminal_reward', sa.Float(), nullable=True),
    sa.Column('turn_distance_to_terminal', sa.Integer(), nullable=True),
    sa.Column('response_text', sa.Text(), nullable=False),
    sa.Column('situation_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_precedent_lookup', 'precedent_traces', ['sop_id', 'action', 'cohort'], unique=False)
    op.create_index('ix_precedent_session_turn', 'precedent_traces', ['session_id', 'turn_index'], unique=False)
    op.create_index(op.f('ix_precedent_traces_created_at'), 'precedent_traces', ['created_at'], unique=False)
    op.create_index(op.f('ix_precedent_traces_project_id'), 'precedent_traces', ['project_id'], unique=False)
    op.create_index(op.f('ix_precedent_traces_sop_id'), 'precedent_traces', ['sop_id'], unique=False)
    op.create_index(op.f('ix_precedent_traces_tenant_id'), 'precedent_traces', ['tenant_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('sop_id', sa.String(length=32), nullable=False),
    sa.Column('sop_version', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('terminal_outcome', sa.String(length=32), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_project_id'), 'sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_sessions_sop_id'), 'sessions', ['sop_id'], unique=False)
    op.create_index(op.f('ix_sessions_tenant_id'), 'sessions', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_tenant_id'), 'api_keys', ['tenant_id'], unique=False)
    op.create_table('corpus_docs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('corpus_id', sa.String(length=32), nullable=False),
    sa.Column('doc_key', sa.String(length=200), nullable=False),
    sa.Column('topic', sa.String(length=200), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['corpus_id'], ['corpora.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('corpus_id', 'doc_key')
    )
    op.create_index(op.f('ix_corpus_docs_corpus_id'), 'corpus_docs', ['corpus_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'slug')
    )
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('turns',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('turn_index', sa.Integer(), nullable=False),
    sa.Column('user_message', sa.Text(), nullable=False),
    sa.Column('assistant_message', sa.Text(), nullable=False),
    sa.Column('cohort', sa.String(length=100), nullable=False),
    sa.Column('mood', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'turn_index')
    )
    op.create_index(op.f('ix_turns_session_id'), 'turns', ['session_id'], unique=False)
    op.create_table('sops',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_sops_project_id'), 'sops', ['project_id'], unique=False)
    op.create_index(op.f('ix_sops_tenant_id'), 'sops', ['tenant_id'], unique=False)
    op.create_table('sop_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('sop_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('definition', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sop_id'], ['sops.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sop_id', 'version')
    )
    op.create_index(op.f('ix_sop_versions_sop_id'), 'sop_versions', ['sop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sop_versions_sop_id'), table_name='sop_versions')
    op.drop_table('sop_versions')
    op.drop_index(op.f('ix_sops_tenant_id'), table_name='sops')
    op.drop_index(op.f('ix_sops_project_id'), table_name='sops')
    op.drop_table('sops')
    op.drop_index(op.f('ix_turns_session_id'), table_name='turns')
    op.drop_table('turns')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_corpus_docs_corpus_id'), table_name='corpus_docs')
    op.drop_table('corpus_docs')
    op.drop_index(op.f('ix_api_keys_tenant_id'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_table('tenants')
    op.drop_index(op.f('ix_sessions_tenant_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_sop_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_project_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_precedent_traces_tenant_id'), table_name='precedent_traces')
    op.drop_index(op.f('ix_precedent_traces_sop_id'), table_name='precedent_traces')
    op.drop_index(op.f('ix_precedent_traces_project_id'), table_name='precedent_traces')
    op.drop_index(op.f('ix_precedent_traces_created_at'), table_name='precedent_traces')
    op.drop_index('ix_precedent_session_turn', table_name='precedent_traces')
    op.drop_index('ix_precedent_lookup', table_name='precedent_traces')
    op.drop_table('precedent_traces')
    op.drop_index(op.f('ix_pool_picks_tenant_id'), table_name='pool_picks')
    op.drop_index(op.f('ix_pool_picks_session_id'), table_name='pool_picks')
    op.drop_index(op.f('ix_pool_picks_project_id'), table_name='pool_picks')
    op.drop_table('pool_picks')
    op.drop_index('ix_fetch_session', table_name='data_fetches')
    op.drop_index(op.f('ix_data_fetches_tenant_id'), table_name='data_fetches')
    op.drop_index(op.f('ix_data_fetches_project_id'), table_name='data_fetches')
    op.drop_table('data_fetches')
    op.drop_index(op.f('ix_corpora_tenant_id'), table_name='corpora')
    op.drop_index(op.f('ix_corpora_project_id'), table_name='corpora')
    op.drop_table('corpora')
    # ### end Alembic commands ###
