"""tenant secrets

Revision ID: 4e0afee78db4
Revises: 133c2b77914a
Create Date: 2026-07-15 07:50:47.601246
"""
from alembic import op
import sqlalchemy as sa


revision = '4e0afee78db4'
down_revision = '133c2b77914a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenant_secrets',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'name')
    )
    op.create_index(op.f('ix_tenant_secrets_tenant_id'), 'tenant_secrets', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tenant_secrets_tenant_id'), table_name='tenant_secrets')
    op.drop_table('tenant_secrets')
    # ### end Alembic commands ###
