"""connectors table + audit connector column

Revision ID: 7b4b2c32b69f
Revises: c26080d9cb39
Create Date: 2026-07-16 05:49:38.868172
"""
from alembic import op
import sqlalchemy as sa


revision = '7b4b2c32b69f'
down_revision = 'c26080d9cb39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connectors',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'name')
    )
    op.create_index(op.f('ix_connectors_project_id'), 'connectors', ['project_id'], unique=False)
    op.create_index(op.f('ix_connectors_tenant_id'), 'connectors', ['tenant_id'], unique=False)
    op.add_column('data_fetches', sa.Column('connector', sa.String(length=100), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_fetches', 'connector')
    op.drop_index(op.f('ix_connectors_tenant_id'), table_name='connectors')
    op.drop_index(op.f('ix_connectors_project_id'), table_name='connectors')
    op.drop_table('connectors')
    # ### end Alembic commands ###
