"""prompt blocks + session bindings (D-7)

Revision ID: 7f8ea45e25e0
Revises: 0a704dda7a76
Create Date: 2026-07-15 01:11:41.220783
"""
from alembic import op
import sqlalchemy as sa


revision = '7f8ea45e25e0'
down_revision = '0a704dda7a76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_blocks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name')
    )
    op.create_index(op.f('ix_prompt_blocks_project_id'), 'prompt_blocks', ['project_id'], unique=False)
    op.create_index(op.f('ix_prompt_blocks_tenant_id'), 'prompt_blocks', ['tenant_id'], unique=False)
    op.create_table('prompt_block_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('block_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['prompt_blocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'version')
    )
    op.create_index(op.f('ix_prompt_block_versions_block_id'), 'prompt_block_versions', ['block_id'], unique=False)
    op.add_column('sessions', sa.Column('prompt_bindings', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'prompt_bindings')
    op.drop_index(op.f('ix_prompt_block_versions_block_id'), table_name='prompt_block_versions')
    op.drop_table('prompt_block_versions')
    op.drop_index(op.f('ix_prompt_blocks_tenant_id'), table_name='prompt_blocks')
    op.drop_index(op.f('ix_prompt_blocks_project_id'), table_name='prompt_blocks')
    op.drop_table('prompt_blocks')
    # ### end Alembic commands ###
