"""turns debug json

Revision ID: 8fd0034b8653
Revises: 7b4b2c32b69f
Create Date: 2026-07-16 06:29:43.873726
"""
from alembic import op
import sqlalchemy as sa


revision = '8fd0034b8653'
down_revision = '7b4b2c32b69f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('turns', sa.Column('debug', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('turns', 'debug')
    # ### end Alembic commands ###
