"""copilot threads, messages, per-tenant memory

Revision ID: 9d299dc7f824
Revises: f1048e08dd81
Create Date: 2026-07-27 01:57:04.595439
"""
from alembic import op
import sqlalchemy as sa


revision = '9d299dc7f824'
down_revision = 'f1048e08dd81'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('copilot_memories',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=True),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_memories_project_id'), 'copilot_memories', ['project_id'], unique=False)
    op.create_index(op.f('ix_copilot_memories_tenant_id'), 'copilot_memories', ['tenant_id'], unique=False)
    op.create_table('copilot_threads',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id')
    )
    op.create_index(op.f('ix_copilot_threads_project_id'), 'copilot_threads', ['project_id'], unique=False)
    op.create_index(op.f('ix_copilot_threads_tenant_id'), 'copilot_threads', ['tenant_id'], unique=False)
    op.create_table('copilot_messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('thread_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('tab', sa.String(length=40), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['copilot_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_copilot_messages_created_at'), 'copilot_messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_copilot_messages_thread_id'), 'copilot_messages', ['thread_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_copilot_messages_thread_id'), table_name='copilot_messages')
    op.drop_index(op.f('ix_copilot_messages_created_at'), table_name='copilot_messages')
    op.drop_table('copilot_messages')
    op.drop_index(op.f('ix_copilot_threads_tenant_id'), table_name='copilot_threads')
    op.drop_index(op.f('ix_copilot_threads_project_id'), table_name='copilot_threads')
    op.drop_table('copilot_threads')
    op.drop_index(op.f('ix_copilot_memories_tenant_id'), table_name='copilot_memories')
    op.drop_index(op.f('ix_copilot_memories_project_id'), table_name='copilot_memories')
    op.drop_table('copilot_memories')
    # ### end Alembic commands ###
