"""session subsystems override

Revision ID: a0d5104ec5df
Revises: 4e0afee78db4
Create Date: 2026-07-15 08:00:15.944438
"""
from alembic import op
import sqlalchemy as sa


revision = 'a0d5104ec5df'
down_revision = '4e0afee78db4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('subsystems_override', sa.String(length=16), nullable=False, server_default=''))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'subsystems_override')
    # ### end Alembic commands ###
