"""ab_tests table

Revision ID: c26080d9cb39
Revises: a0d5104ec5df
Create Date: 2026-07-16 02:15:33.886285
"""
from alembic import op
import sqlalchemy as sa


revision = 'c26080d9cb39'
down_revision = 'a0d5104ec5df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_tests',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('sop_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('arm_a_version', sa.Integer(), nullable=False),
    sa.Column('arm_b_version', sa.Integer(), nullable=False),
    sa.Column('n_sessions', sa.Integer(), nullable=False),
    sa.Column('max_turns', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('progress', sa.JSON(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_tests_created_at'), 'ab_tests', ['created_at'], unique=False)
    op.create_index(op.f('ix_ab_tests_project_id'), 'ab_tests', ['project_id'], unique=False)
    op.create_index(op.f('ix_ab_tests_sop_id'), 'ab_tests', ['sop_id'], unique=False)
    op.create_index(op.f('ix_ab_tests_tenant_id'), 'ab_tests', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ab_tests_tenant_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_sop_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_project_id'), table_name='ab_tests')
    op.drop_index(op.f('ix_ab_tests_created_at'), table_name='ab_tests')
    op.drop_table('ab_tests')
    # ### end Alembic commands ###
