"""config_documents tables

Revision ID: f1048e08dd81
Revises: f2624f6bc2a6
Create Date: 2026-07-26 02:42:12.644839
"""
from alembic import op
import sqlalchemy as sa


revision = 'f1048e08dd81'
down_revision = 'f2624f6bc2a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_documents',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'name')
    )
    op.create_index(op.f('ix_config_documents_project_id'), 'config_documents', ['project_id'], unique=False)
    op.create_index(op.f('ix_config_documents_tenant_id'), 'config_documents', ['tenant_id'], unique=False)
    op.create_table('config_document_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('document_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['config_documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id', 'version')
    )
    op.create_index(op.f('ix_config_document_versions_document_id'), 'config_document_versions', ['document_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_document_versions_document_id'), table_name='config_document_versions')
    op.drop_table('config_document_versions')
    op.drop_index(op.f('ix_config_documents_tenant_id'), table_name='config_documents')
    op.drop_index(op.f('ix_config_documents_project_id'), table_name='config_documents')
    op.drop_table('config_documents')
    # ### end Alembic commands ###
