"""config_analysis_reports tables

Revision ID: f2624f6bc2a6
Revises: f9bca90e0e4a
Create Date: 2026-07-26 01:04:38.991528
"""
from alembic import op
import sqlalchemy as sa


revision = 'f2624f6bc2a6'
down_revision = 'f9bca90e0e4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_analysis_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('tenant_id', sa.String(length=32), nullable=False),
    sa.Column('project_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('latest_version', sa.Integer(), nullable=False),
    sa.Column('published_version', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'project_id', 'name')
    )
    op.create_index(op.f('ix_config_analysis_reports_project_id'), 'config_analysis_reports', ['project_id'], unique=False)
    op.create_index(op.f('ix_config_analysis_reports_tenant_id'), 'config_analysis_reports', ['tenant_id'], unique=False)
    op.create_table('config_analysis_report_versions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('report_id', sa.String(length=32), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['report_id'], ['config_analysis_reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id', 'version')
    )
    op.create_index(op.f('ix_config_analysis_report_versions_report_id'), 'config_analysis_report_versions', ['report_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_config_analysis_report_versions_report_id'), table_name='config_analysis_report_versions')
    op.drop_table('config_analysis_report_versions')
    op.drop_index(op.f('ix_config_analysis_reports_tenant_id'), table_name='config_analysis_reports')
    op.drop_index(op.f('ix_config_analysis_reports_project_id'), table_name='config_analysis_reports')
    op.drop_table('config_analysis_reports')
    # ### end Alembic commands ###
