"""config_ruleset_versions schema column

Revision ID: f9bca90e0e4a
Revises: 21e2e51b824a
Create Date: 2026-07-25 01:22:10.457395
"""
from alembic import op
import sqlalchemy as sa


revision = 'f9bca90e0e4a'
down_revision = '21e2e51b824a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('config_ruleset_versions', sa.Column('config_schema', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('config_ruleset_versions', 'config_schema')
    # ### end Alembic commands ###
