"""sop version provenance (source document)

Revision ID: fedba019c93a
Revises: 7f8ea45e25e0
Create Date: 2026-07-15 02:54:18.476955
"""
from alembic import op
import sqlalchemy as sa


revision = 'fedba019c93a'
down_revision = '7f8ea45e25e0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sop_versions', sa.Column('source_document', sa.Text(), nullable=True))
    op.add_column('sop_versions', sa.Column('source_filename', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sop_versions', 'source_filename')
    op.drop_column('sop_versions', 'source_document')
    # ### end Alembic commands ###
